# Ansible Inventory
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
  vars:
    # User configuration
    user_name: "{{ lookup('env', 'USER') }}"
    user_home: "{{ lookup('env', 'HOME') }}"
    dotfiles_dir: "{{ user_home }}/dotfiles"
    
    # Theme configuration
    theme_name: "material-darker"
